### ISSUE TITLE
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds

### ISSUE THREAD

**Issue by EmeraldGamer124** [DarkReaper231/Incredibox#4]
node:internal/buffer:84
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
←[90m    at new NodeError (node:internal/errors:387:5)←[39m
←[90m    at boundsError (node:internal/buffer:84:11)←[39m
←[90m    at Buffer.readUInt32LE (node:internal/buffer:220:5)←[39m
    at Pickle.getPayloadSize (C:\Users\thepi\AppData\Roaming\npm\node_modules\←[4masar←[24m\node_modules\←[4mchromium-pickle-js←[24m\lib\pickle.js:192:24)
    at new PickleIterator (C:\Users\thepi\AppData\Roaming\npm\node_modules\←[4masar←[24m\node_modules\←[4mchromium-pickle-js←[24m\lib\pickle.js:27:28)
    at Pickle.createIterator (C:\Users\thepi\AppData\Roaming\npm\node_modules\←[4masar←[24m\node_modules\←[4mchromium-pickle-js←[24m\lib\pickle.js:144:12)
    at Object.module.exports.readArchiveHeaderSync (C:\Users\thepi\AppData\Roaming\npm\node_modules\←[4masar←[24m\lib\disk.js:68:23)
    at Object.module.exports.readFilesystemSync (C:\Users\thepi\AppData\Roaming\npm\node_modules\←[4masar←[24m\lib\disk.js:84:25)
    at Object.module.exports.extractAll (C:\Users\thepi\AppData\Roaming\npm\node_modules\←[4masar←[24m\lib\asar.js:174:27)
    at Command.<anonymous> (C:\Users\thepi\AppData\Roaming\npm\node_modules\←[4masar←[24m\bin\asar.js:72:10) {
  code: ←[32m'ERR_BUFFER_OUT_OF_BOUNDS'←[39m

Every time I try to extract the source code, it brings me this error. Please help.

**Comment by EmeraldGamer124** [comment]
Every time I try to extract the source code, it brings me this error. Please help.

**Comment by DarkReaper231** [comment]
Download Visual Studio Code, then download this addon to VS Code:
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

Click on FIles, open folder, select Incredibox project folder and open it. Then right click on the index.html file and press Live Server
